### PR TITLE
Support 64-bit architecture in install script

### LINKED ISSUE #5: When running on aarch64, the wrong dotnet downloads are installed
Thanks for providing this install script.  It definitely makes things easier.

When running the install.sh script on Raspberry Pi OS 64bit version, the 32 bit versions are installed, which seems to work but running dotnet gives an error:
dotnet: error while loading shared libraries: libstdc++.so.6

I changed the arm32 to arm64 in the download path and the script seems to work fine.

### PR DESCRIPTION
**Pull request by MarkXA**
Download ARM64 packages if 64-bit processor detected, otherwise ARM32. Fixes #5

### CODE REVIEW

**Comment by theStanister** [comment]
FWIW I just tested this on my Pi4B 8GB, aside from "exit" on line 118 which I had to comment out on my local copy, appears to have installed correctly for me.. thanks heaps

**Review by pjgpetecodes — APPROVED** [review]
Fab stuff @MarkXA! Thanks!

**Comment by theStanister** [comment]
@pjgpetecodes  btw did you comment out the "exit" on line 118 before the merge by any chance? That effectively exits the script and no longer proceeds to the installation further down the script (ie: basically just downloads the correct arm64 package but doesnt install). Presumably was added during testing but forgotten before checking in the code... Hence my note above that the line needed to be commented out in order for the actual installation to take place. or at least did in my case. I'm not expert at shell script dev tho so please double check it in case there are other conditions that needed to be considered. thx!

**Comment by pjgpetecodes** [comment]
Great point! Just removed it!

**Pull request merged**
